### ISSUE TITLE
No handlers could be found for logger "rdflib.term"

### ISSUE THREAD

**Issue by dattachandan** [smart-classic/smart_sample_apps#57]
python generate_readme.py > README

No handlers could be found for logger "rdflib.term"
Traceback (most recent call last):
  File "generate_readme.py", line 5, in <module>
    from client import SMARTClient
  File "D:\work\src\pythonworkspace\smart_sample_apps\smart_client\client.py", l
ine 12, in <module>
    from generate_api import SmartResponse, augment
  File "D:\work\src\pythonworkspace\smart_sample_apps\smart_client\generate_api.
py", line 9, in <module>
    import common.rdf_tools.rdf_ontology as rdf_ontology
  File "D:\work\src\pythonworkspace\smart_sample_apps\smart_client\common\rdf_to
ols\rdf_ontology.py", line 513, in <module>
    parse_ontology(f)
  File "D:\work\src\pythonworkspace\smart_sample_apps\smart_client\common\rdf_to
ols\rdf_ontology.py", line 480, in parse_ontology
    m = parse_rdf(f)
  File "D:\work\src\pythonworkspace\smart_sample_apps\smart_client\common\rdf_to
ols\util.py", line 44, in parse_rdf
    model.default_context.parse(data=string, format="n3")
  File "build\bdist.win-amd64\egg\rdflib\graph.py", line 1035, in parse
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 188
7, in parse
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 185
8, in parse
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 422
, in loadStream
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 428
, in loadBuf
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 454
, in feed
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 477
, in directiveOrStatement
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 114
7, in checkDot
  File "build\bdist.win-amd64\egg\rdflib\plugins\parsers\notation3.py", line 160
3, in BadSyntax
rdflib.plugins.parsers.notation3.BadSyntax: at line 6 of <>:
Bad syntax (expected '.' or '}' or ']' at end of statement) at ^ in:
"...ms/" >
    <!ENTITY foaf "http://xmlns.com/foaf/0.1/" >
    ^<!ENTITY owl "http://www.w3.org/2002/07/owl#" >
    <!ENTITY..."

**Comment by nschwertner** [comment]
Sounds like a problem with the rdflib version. Did you follow precisely the installation steps at:
http://docs.smartplatforms.org/framework/reference-implementation/install-ubuntu.html

Note the specific version requirement for some libs:
`sudo easy_install -U "rdflib==3.2.3" "rdfextras==0.2" "jsonschema==0.7" httplib2`

**Comment by dattachandan** [comment]
Hi,
I am doing all my installs on a win7x64 machine with JDK 1.6

On Sat, May 17, 2014 at 12:48 AM, nschwertner notifications@github.comwrote:

> Sounds like a problem with the rdflib version. Did you follow precisely
> the installation steps at:
> 
> http://docs.smartplatforms.org/framework/reference-implementation/install-ubuntu.html
> 
> Note the specific version requirement for some libs:
> sudo easy_install -U "rdflib==3.2.3" "rdfextras==0.2" "jsonschema==0.7"
> httplib2
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chb/smart_sample_apps/issues/57#issuecomment-43327008
> .

## 

Regards,
Chandan

**Comment by dattachandan** [comment]
Is it possible to install the sample apps without installing the server and test out the sample apps in the SMART sandbox?

**Comment by nschwertner** [comment]
If by "server" you mean the complete SMART reference container stack, then the answer is YES... you can test against the sandbox.

If by "server" you mean the sample apps server, then the answer is NO... you need to serve the apps on an HTTP server one way or another. You can, of course, use a different server than the Django server that we provide.

**Comment by dattachandan** [comment]
Yes, by server I meant the SMART ref container(https://github.com/chb/smart_server/). 

I want to test the sample apps on the sandbox without installing the reference container locally. I think if this is possible, then I had tried to build the smart_sample_apps without installing the reference container and had got the error.

**Comment by nschwertner** [comment]
The smart_sample_apps server by itself has no dependencies on the other two servers in the SMART reference container. The error you got when fetching the repository with git is unrelated.
